### ISSUE TITLE
No OAuth URL in terminal 

### ISSUE THREAD

**Issue by juanhaywood** [greghesp/assistant-relay#108]
It took me a few days, but I finally found the reason why I was not getting the OAuth URL for use on headless installations. 

Firstly I thought it was me not following instructions correctly, but after starting from scratch 6 times, I realized it's not me not following the instructions. After all, I successfully got AR working 3 months ago. Why could I not get it to work now?

I then tried different versions of node, different flavours of linux (Ubuntu/Debian), but in all cases, no URL was presented in the terminal.

Then, luckily, I noticed on the GitHub page for this project that there was a recent commit (24 days ago). I checked out the older commit instead and tried again, and voila. Everything working. Well, except for the "Exited with code 3" error, but this did not stop me from getting the URL, and pasting the code.

So, there is something wrong with the latest commit.

Here is my terminal output, first attempting with the current commit, then with the previous commit:

```
user@instance-2:~/assistant-relay$ sudo n 8
   installed : v8.16.1 (with npm 6.4.1)
user@instance-2:~/assistant-relay$ npm run start

> assistant-relay@2.1.1 start /home/user/assistant-relay
> node server/app.js

Opening OAuth URL. Return here with your code.
Paste your code: ^C
user@instance-2:~/assistant-relay$ cd
user@instance-2:~$ rm -R assistant-relay/
rm: remove write-protected regular file 'assistant-relay/.git/objects/pack/pack-86fa66f9b51bf1ab9e54426ded1cd2102ba4bcd2.pack'? y
rm: remove write-protected regular file 'assistant-relay/.git/objects/pack/pack-86fa66f9b51bf1ab9e54426ded1cd2102ba4bcd2.idx'? y
user@instance-2:~$ git clone https://github.com/greghesp/assistant-relay.git
Cloning into 'assistant-relay'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 502 (delta 0), reused 2 (delta 0), pack-reused 498
Receiving objects: 100% (502/502), 2.67 MiB | 0 bytes/s, done.
Resolving deltas: 100% (244/244), done.
user@instance-2:~$ cd assistant-relay/
user@instance-2:~/assistant-relay$ git checkout 1b935f3bf0d59f9a5152da86aa670da1706d70ba
Note: checking out '1b935f3bf0d59f9a5152da86aa670da1706d70ba'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1b935f3... package version update
user@instance-2:~/assistant-relay$ npm install

> grpc@1.8.0 install /home/user/assistant-relay/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/home/user/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote
npm WARN assistant-relay@2.1.1 No repository field.

added 382 packages from 264 contributors and audited 910 packages in 9.22s
found 49 vulnerabilities (3 low, 29 moderate, 17 high)
  run `npm audit fix` to fix them, or `npm audit` for details
user@instance-2:~/assistant-relay$ cd
user@instance-2:~$ ls
assistant-relay
user@instance-2:~$ mv juan.json assistant-relay/server/configurations/secrets/
user@instance-2:~$ cd assistant-relay/server/configurations
user@instance-2:~/assistant-relay/server/configurations$ sudo nano config.json 
user@instance-2:~/assistant-relay/server/configurations$ cd
user@instance-2:~$ cd assistant-relay/
user@instance-2:~/assistant-relay$ npm run start

> assistant-relay@2.1.1 start /home/user/assistant-relay
> node server/app.js

Attempted to automatically open the URL, but if it failed, copy/paste this in your browser:
 https://accounts.google.com/o/oauth2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&response_type=code&client_id=175329715972-2vhfl7u5glrsjnif19ih5oi51gh5q2t6.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
Paste your code: (node:4511) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/user/assistant-relay/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:4511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4511) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^Cuser@instance-2:~/assistant-relay$ 
user@instance-2:~/assistant-relay$ node -v
v8.16.1
user@instance-2:~/assistant-relay$ npm run start

> assistant-relay@2.1.1 start /home/user/assistant-relay
> node server/app.js

Attempted to automatically open the URL, but if it failed, copy/paste this in your browser:
 https://accounts.google.com/o/oauth2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&response_type=code&client_id=175329715972-2vhfl7u5glrsjnif19ih5oi51gh5q2t6.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
Paste your code: (node:4574) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/user/assistant-relay/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:4574) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4574) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
4/rwFVgENtYnzM-bKE2L9wIU3N-hfx2cztifKH26IJsXg_OEBoP6FG6AE
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄                    ▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄     ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄         ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄       ▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄                    ▄▄▄▄▄    ▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄                     ▄▄▄▄▄ ▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

Assistant Relay is now setup and running for juan 

You can now visit http://ip-address:3000 in a browser, or send POST requests to it

```

**Comment by ryancasler** [comment]
It appears that the authentication method changed in the latest release of the google-assistant from Endoplasmic totally changing the authorization structure.  I have no idea what it will take to get that working but it is definitely more than just updating to the latest version.  You'll definitely have to run with v 0.2.0 of the google assistant library until Greg updates the rest of the code for Assistant Relay.

**Comment by juanhaywood** [comment]
Thanks. I just thought I'd post incase someone else runs into the same issue, hopefully I can save them some troubleshooting time. 

If I use my method above to authenticate the app, and then update AR afterward, would it still work? If so, what is the update path/method (sorry, bit of a noob)?

**Comment by ryancasler** [comment]
Actually, what you did was a lot more complicated than you had to be.  After the git clone, all you would have had to do was go into the package.json file and modify

`    "google-assistant": "^0.6.0",`

to 

`    "google-assistant": "^0.2.0",`

And then do the rest of the setup.

**Comment by juanhaywood** [comment]
*insert facepalm*

Thanks

**Comment by ryancasler** [comment]
no problem.

**Comment by greghesp** [comment]
@ryancasler is right.  Seems the way it authorises has changed, however that being said it still works for me on a fresh install.

I've ended up writing my own auth structure for V3, extending the auth method from the google-assistant library so that you dont have to mess around with console commands any more

**Comment by greghesp** [comment]
Accidentally closed...again

**Comment by greghesp** [comment]
Could you try V3.  It utilises a web UI now
