### ISSUE TITLE
Can this run with readonly filesystem?

### ISSUE THREAD

**Issue by mrisher** [greghesp/assistant-relay#146]
Attempting to run assistant-relay on App Engine, but unfortunately the app tries to open `config.json` with write permissions, yielding an error. Has anyone looked at making a readonly mode? I am new to the app but would assume that once it's configured (which could be done locally), the running app doesn't need to write to the json file.

```
2020-01-01 07:48:54 default[20191231t233727]  0|www  | { Error: EROFS: read-only file system, open './bin/config.json'
2020-01-01 07:48:54 default[20191231t233727]  0|www  |     at Object.openSync (fs.js:443:3)
2020-01-01 07:48:54 default[20191231t233727]  0|www  |     at writeFileSync (fs.js:1194:35)
2020-01-01 07:48:54 default[20191231t233727]  0|www  |     at FileSync.write (/srv/node_modules/lowdb/adapters/FileSync.js:53:14)
...
2020-01-01 07:48:54 default[20191231t233727]  0|www  |     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
2020-01-01 07:48:54 default[20191231t233727]  0|www  |   errno: -30,
2020-01-01 07:48:54 default[20191231t233727]  0|www  |   syscall: 'open',
2020-01-01 07:48:54 default[20191231t233727]  0|www  |   code: 'EROFS',
2020-01-01 07:48:54 default[20191231t233727]  0|www  |   path: './bin/config.json' }
```

**Comment by ryancasler** [comment]
But the configuration is saved in that JSON file.  How else would it get the config when it reboots?  

I don't understand what you mean by "done locally"...the app has to run locally on your network or it won't work.  That's how it detects your Google Home devices.  The Google Assistant SDK is limited to those devices that it sees as local for what it can use.  So, you can't run this in the cloud .

**Comment by mrisher** [comment]
Oh, my mistake. I didn't realize the app needed to run locally. I saw the sample code for the Raspbery Pi but assumed the Assistant SDK would connect using the account that matches the OAuth credentials. If that's not the case, this is moot; otherwise, I thought I could run it in an appless cloud service, where it would read a hand-updated config JSON. Thanks for the reply!

**Comment by ryancasler** [comment]
No problem.  The reason it won't is because of security restrictions in place in the Assistant SDK.  To prevent people from accessing your devices, the Assistant SDK is limited to devices on the local network.  That way no one could try and trojan horse something onto your network.
