### ISSUE TITLE
Failed at assistant-relay start script

### ISSUE THREAD

**Issue by ripvega** [greghesp/assistant-relay#154]
**Describe the bug**
Hi.

I'm not really sure if this is the right place to get help with this but I've tried the install and am now stuck.

I get the following:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.13.6
3 info using node@v13.7.0
4 verbose config Skipping project config: /Users/ashscott/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle assistant-relay@3.2.0~prestart: assistant-relay@3.2.0
7 info lifecycle assistant-relay@3.2.0~start: assistant-relay@3.2.0
8 verbose lifecycle assistant-relay@3.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle assistant-relay@3.2.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ashscott/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle assistant-relay@3.2.0~start: CWD: /Users/ashscott
11 silly lifecycle assistant-relay@3.2.0~start: Args: [ '-c', 'pm2 start ./bin/www && pm2 log www' ]
12 silly lifecycle assistant-relay@3.2.0~start: Returned: code: 1  signal: null
13 info lifecycle assistant-relay@3.2.0~start: Failed to exec start script
14 verbose stack Error: assistant-relay@3.2.0 start: `pm2 start ./bin/www && pm2 log www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:321:20)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:321:20)
14 verbose stack     at maybeClose (internal/child_process.js:1026:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
15 verbose pkgid assistant-relay@3.2.0
16 verbose cwd /Users/ashscott
17 verbose Darwin 18.2.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
19 verbose node v13.7.0
20 verbose npm  v6.13.6
21 error code ELIFECYCLE
22 error errno 1
23 error assistant-relay@3.2.0 start: `pm2 start ./bin/www && pm2 log www`
23 error Exit status 1
24 error Failed at the assistant-relay@3.2.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```
 I don't know where to go from here. Any pointers will be much appreciated. I'm on UK time so apologies if a reply takes a while.

Running on a Mac mini with Mojave.

Ash

**Comment by greghesp** [comment]
Do you have PM2 installed?

**Comment by ripvega** [comment]
Thanks for the reply, Greg.

I started again and it now runs. Good work with it. Thank you.

The only issue I'm left with is after a restart of the Mac it's running on
I have to use terminal again and restart it.

Is there a way to have it always self start at login?

Many thanks.

**Comment by greghesp** [comment]
Not something I've tried, but you could create a .sh script that launches AR with PM2, and then add that to autostart with https://www.soma-zone.com/LaunchControl/
