### ISSUE TITLE
Unable to Install on Ubuntu Server

### ISSUE THREAD

**Issue by ryancasler** [greghesp/assistant-relay#182]
I am not able to install on Ubuntu Server.  After running sudo npm run setup, I get the following debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@6.14.5
3 info using node@v12.18.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle assistant-relay@3.3.2~presetup: assistant-relay@3.3.2
6 info lifecycle assistant-relay@3.3.2~setup: assistant-relay@3.3.2
7 verbose lifecycle assistant-relay@3.3.2~setup: unsafe-perm in lifecycle true
8 verbose lifecycle assistant-relay@3.3.2~setup: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ryan/Assistant_Relay/node_module>
9 verbose lifecycle assistant-relay@3.3.2~setup: CWD: /home/ryan/Assistant_Relay
10 silly lifecycle assistant-relay@3.3.2~setup: Args: [ '-c', 'npm i -g pm2 && npm i' ]
11 silly lifecycle assistant-relay@3.3.2~setup: Returned: code: 1  signal: null
12 info lifecycle assistant-relay@3.3.2~setup: Failed to exec setup script
13 verbose stack Error: assistant-relay@3.3.2 setup: `npm i -g pm2 && npm i`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid assistant-relay@3.3.2
15 verbose cwd /home/ryan/Assistant_Relay
16 verbose Linux 5.4.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
18 verbose node v12.18.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error assistant-relay@3.3.2 setup: `npm i -g pm2 && npm i`
22 error Exit status 1
23 error Failed at the assistant-relay@3.3.2 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

I tried without sudo and that fails to install at all because it doesn't have the correct permissions.  I have downloaded a new copy of release.zip and I have tried building in Docker.  Nothing seems to work.  I get the following error when I try and run via sudo npm run start.
```
0|www  | Error: Failed to load gRPC binary module because it was not installed for the current system
0|www  | Expected directory: node-v72-linux-x64-glibc
0|www  | Found: [node-v64-linux-x64-glibc]
0|www  | This problem can often be fixed by running "npm rebuild" on the current system
0|www  | Original error: Cannot find module '/home/ryan/GAR/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
0|www  | Require stack:
0|www  | - /home/ryan/GAR/node_modules/grpc/src/grpc_extension.js
0|www  | - /home/ryan/GAR/node_modules/grpc/src/client_interceptors.js
0|www  | - /home/ryan/GAR/node_modules/grpc/src/client.js
0|www  | - /home/ryan/GAR/node_modules/grpc/index.js
0|www  | - /home/ryan/GAR/node_modules/google-assistant/components/assistant.js
0|www  | - /home/ryan/GAR/helpers/server.js
0|www  | - /home/ryan/GAR/app.js
0|www  | - /home/ryan/GAR/bin/www
0|www  |     at Object.<anonymous> (/home/ryan/GAR/node_modules/grpc/src/grpc_extension.js:53:17)
0|www  |     at Module._compile (internal/modules/cjs/loader.js:1138:30)
0|www  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
0|www  |     at Module.load (internal/modules/cjs/loader.js:986:32)
0|www  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
0|www  |     at Module.require (internal/modules/cjs/loader.js:1026:19)
0|www  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|www  |     at require (internal/modules/cjs/helpers.js:72:18)
0|www  |     at Object.<anonymous> (/home/ryan/GAR/node_modules/grpc/src/client_interceptors.js:144:12)
0|www  |     at Module._compile (internal/modules/cjs/loader.js:1138:30) {
0|www  |   code: 'MODULE_NOT_FOUND'
0|www  | }
```
I noticed that there have been several changes since the last release.   Do we have to update each of those files manually?  I don't understand how to go from the repo here to a release.zip file, so I have no idea what to do other than update each file one at a time.  Some assistance would be appreciated.

**Comment by 6uhrmittag** [comment]
I just found this tool and run into multiple npm issues to. After starting with a fresh vagrant box, I just did
1. `sudo npm i pm2 -g`
2. `npm i` (because `npm setup` gives a permssion error)

and it finally worked fine. Remove the `node_modules` when starting fresh. 
(I'm using Ubuntu bionic + node 12)

**Comment by ryancasler** [comment]
> Remove the `node_modules` when starting fresh.

Ah....I will give that a shot.

**Comment by ryancasler** [comment]
That was it.  removing the node modules folder and running in a node v12 docker image worked!  Thanks!
