### ISSUE TITLE
please help can't figure out what I'm doing wrong

### ISSUE THREAD

**Issue by DaveR2419** [greghesp/assistant-relay#211]
pi@raspberrypi:~/assistant relay $ npm run start

> assistant-relay@3.3.2 start /home/pi/assistant relay
> pm2 start ./bin/www && pm2 log www

[PM2] Spawning PM2 daemon with pm2_home=/home/pi/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /home/pi/assistant relay/bin/www in fork_mode (1 instance)
[PM2] Done.
┌─────┬────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name   │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ www    │ default     │ 3.3.2   │ fork    │ 1413     │ 0s     │ 0    │ online    │ 0%       │ 23.3mb   │ pi       │ disabled │
└─────┴────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[TAILING] Tailing last 15 lines for [www] process (change the value with --lines option)
/home/pi/.pm2/logs/www-out.log last 15 lines:
0|www      | Assistant Relay Server Initialized
0|www      | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure
0|www      | An update is available. Please visit https://github.com/greghesp/assistant-relay/releases
0|www      | Assistant Relay Server Initialized
0|www      | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure
0|www      | Assistant Relay Server Initialized
0|www      | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure
0|www      | Assistant Relay Server Initialized
0|www      | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure
0|www      | Assistant Relay Server Initialized
0|www      | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure
0|www      | Assistant Relay Server Initialized
0|www      | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure
0|www      | Assistant Relay Server Initialized
0|www      | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure

/home/pi/.pm2/logs/www-error.log last 15 lines:
0|www      |    'Getting metadata from plugin failed with error: Cannot read property \'access_token\' of undefined' }
0|www      | Update check failed. You've probably been rate limited by GitHub
0|www      | Auth error:TypeError: Cannot read property 'access_token' of undefined
0|www      | { Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: Cannot read property 'access_token' of undefined
0|www      |     at Object.exports.createStatusError (/home/pi/assistant relay/node_modules/grpc/src/common.js:91:15)
0|www      |     at ClientDuplexStream._emitStatusIfDone (/home/pi/assistant relay/node_modules/grpc/src/client.js:233:26)
0|www      |     at ClientDuplexStream._receiveStatus (/home/pi/assistant relay/node_modules/grpc/src/client.js:211:8)
0|www      |     at Object.onReceiveStatus (/home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:1311:15)
0|www      |     at InterceptingListener._callNext (/home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:568:42)
0|www      |     at InterceptingListener.onReceiveStatus (/home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:618:8)
0|www      |     at /home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:1127:18
0|www      |   code: 14,
0|www      |   metadata: Metadata { _internal_repr: {}, flags: 0 },
0|www      |   details:
0|www      |    'Getting metadata from plugin failed with error: Cannot read property \'access_token\' of undefined' }

0|www  | Update check failed. You've probably been rate limited by GitHub
0|www  | Assistant Relay Server Initialized
0|www  | Visit http://192.168.1.49:3000 or http://ar.local:3000 in a browser to configure
0|www  | Auth error:TypeError: Cannot read property 'access_token' of undefined
0|www  | { Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: Cannot read property 'access_token' of undefined
0|www  |     at Object.exports.createStatusError (/home/pi/assistant relay/node_modules/grpc/src/common.js:91:15)
0|www  |     at ClientDuplexStream._emitStatusIfDone (/home/pi/assistant relay/node_modules/grpc/src/client.js:233:26)
0|www  |     at ClientDuplexStream._receiveStatus (/home/pi/assistant relay/node_modules/grpc/src/client.js:211:8)
0|www  |     at Object.onReceiveStatus (/home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:1311:15)
0|www  |     at InterceptingListener._callNext (/home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:568:42)
0|www  |     at InterceptingListener.onReceiveStatus (/home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:618:8)
0|www  |     at /home/pi/assistant relay/node_modules/grpc/src/client_interceptors.js:1127:18
0|www  |   code: 14,
0|www  |   metadata: Metadata { _internal_repr: {}, flags: 0 },
0|www  |   details:
0|www  |    'Getting metadata from plugin failed with error: Cannot read property \'access_token\' of undefined' }
0|www  | Update check failed. You've probably been rate limited by GitHub

**Comment by 6uhrmittag** [comment]
You should add more details here... Do you get an error in the browser?

Issue #186 describes an issue with cloned repos, which sounds somewhat similar. You should download the release .zip, if this is the case.
