### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by spicerackk** [greghesp/assistant-relay#230]
**Describe the bug**
TypeError: Cannot read property '0' of undefined

**To Reproduce**
1. Go to 'sandbox'
2. Enter username and command
3. Hit Submit
4. Get network error

**Expected behavior**
Command would be sent via sandbox

**Screenshots**

**Desktop (please complete the following information):**
-  Platform Raspberry Pi 3B+
 - Browser Opera
 - Version 0.7.4

**Additional context**
Logs repeat these lines

```0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.4:3000 in a browser to configure
0|www  | An update is available. Please visit https://github.com/greghesp/assistant-relay/releases
0|www  | TypeError: Cannot read property 'getRequestHeaders' of undefined
0|www  |     at getAuthorizationHeaderFromGoogleCredential (/assistant_relay/node_modules/grpc/src/credentials.js:188:32)
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:219:5
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:166:5```

**Comment by ryancasler** [comment]
Have you completed the installation of your user correctly?  What command are you entering into the Sandbox?  Can you provide a screenshot?

**Comment by Betanu701** [comment]
Most likely this is because of your client_secret file. You probably are missing
`
 "redirect_uris": ["https://****.firebaseapp.com/__/auth/handler"]  `
 `
 
If you open your client secret file, add this before client_secret. To get the URL, You can try localhost, however you may need to go to OAth and look at the original key that was created. It should have the URLs in it
