### ISSUE TITLE
throws some api error

### ISSUE THREAD

**Issue by realjax** [greghesp/assistant-relay#240]
**Describe the bug**
doesnt work, shows endless repeats of this error 👍 
{ Error: 7 PERMISSION_DENIED: Google Assistant API has not been used in project 1080391690916 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/embeddedassistant.googleapis.com/overview?project=1080391690916 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
0|www  |     at Object.exports.createStatusError (/Users/jaccohuysmans/Applications/assistant-relay/node_modules/grpc/src/common.js:91:15)
0|www  |     at ClientDuplexStream._emitStatusIfDone (/Users/jaccohuysmans/Applications/assistant-relay/node_modules/grpc/src/client.js:233:26)
0|www  |     at ClientDuplexStream._receiveStatus (/Users/jaccohuysmans/Applications/assistant-relay/node_modules/grpc/src/client.js:211:8)
0|www  |     at Object.onReceiveStatus (/Users/jaccohuysmans/Applications/assistant-relay/node_modules/grpc/src/client_interceptors.js:1311:15)
0|www  |     at InterceptingListener._callNext (/Users/jaccohuysmans/Applications/assistant-relay/node_modules/grpc/src/client_interceptors.js:568:42)
0|www  |     at InterceptingListener.onReceiveStatus (/Users/jaccohuysmans/Applications/assistant-relay/node_modules/grpc/src/client_interceptors.js:618:8)
0|www  |     at /Users/jaccohuysmans/Applications/assistant-relay/node_modules/grpc/src/client_interceptors.js:1127:18

**To Reproduce**
just install and follow instructions

**Expected behavior**
I expected it to work

**Desktop (please complete the following information):**
Macos, version 11.1

**Comment by realjax** [comment]
ps. following the link and enabling the API does not solve the problem.
