### ISSUE TITLE
Cannot read properties of undefined (reading 'converse')

### ISSUE THREAD

**Issue by nbortolussi** [greghesp/assistant-relay#282]
Followed all directions for setup, created a user named Nick, but get the following message when trying to run a command in Sandbox.

{
    "user": "Nick",
    "preset": "lunch",
    "command": "hey",
    "broadcast": true
}

TypeError: Cannot read properties of undefined (reading 'converse')
    at new Conversation (/Users/nbortolussi/Downloads/release/node_modules/google-assistant/components/conversation.js:136:34)
    at /Users/nick/Downloads/release/helpers/assistant.js:19:38
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
POST /assistant 500 32.885 ms - 56

Any ideas what this could be?

**Comment by nbortolussi** [comment]
This was due to the auth code not being correct when verifying the user.
