### ISSUE TITLE
Unable to get google connected when doing test query.

### ISSUE THREAD

**Issue by mkono87** [greghesp/assistant-relay#39]
Not sure if im doing something wrong or google is down but when I try to connect with my dev project id and model is  i get

`INFO:root:Connecting to embeddedassistant.googleapis.com
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-pushtotalk", line 11, in <modul                                                                                             e>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __                                                                                             call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in ma                                                                                             in
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in in                                                                                             voke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in in                                                                                             voke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pu                                                                                             shtotalk.py", line 351, in main
    flush_size=audio_flush_size
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/au                                                                                             dio_helpers.py", line 190, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1263, in                                                                                              __init__
    **_remove_self(locals()))
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 680, in _                                                                                             _init__
    samplerate)
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2489, in                                                                                              _get_stream_parameters
    info = query_devices(device)
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 487, in q                                                                                             uery_devices
    raise PortAudioError('Error querying device {0}'.format(device))
sounddevice.PortAudioError: Error querying device -1`

**Comment by greghesp** [comment]
Did you manage to get this resolved?

**Comment by mkono87** [comment]
Yes I finally did, but I cant remember what the issue was.
