### ISSUE TITLE
Issue with index.js at first launch

### ISSUE THREAD

**Issue by ryancasler** [greghesp/assistant-relay#44]
I get the following error when I attempt to install now which i never got before:
```
Paste your code: (node:19205) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/pi/assistant-relay/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:19205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19205) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Dunno what is causing that.  Could it be the version of Node that I'm trying to use?  I'm using 8.11.3.  Also, all of my activity is showing up in My Activity in google but not getting any broadcasts.

**Comment by greghesp** [comment]
That's strange.  Can you try changing your version of Node.  I've got it running on 8.9 without an issue.

Also, do you have a browser installed on the Pi?

**Comment by ryancasler** [comment]
I'll have to try with the older version of Node at some point.  I believe that stretch comes with Chromium installed by default, doesn't it?  Or are you using Stretch lite?
But I am also doing the setup on a headless unit through SSH which always worked before.  You just had to copy the link into a browser on your PC instead of launching from terminal.  Could that be the issue?  Do you have to launch it from the Pi desktop?

**Comment by greghesp** [comment]
I've got a Windows server I run it on, I haven't tried running it on the Pi.
Its using https://www.npmjs.com/package/opn to open the browser so it shouldn't be an issue

**Comment by ryancasler** [comment]
Which version 8.9 of node?  I see v8.9.0 - 8.9.4.

**Comment by greghesp** [comment]
Can you try installing V2 as fresh and running that?

**Comment by ryancasler** [comment]
Which version of Node did you want me to try on?  You said 8.9 but there are 5 8.9's.  :-)  Don't want to have to repeat it again.  Sorry it's taken me a while to get back, Work schedule has heated up and I've been doing a bunch of traveling.

**Comment by readeral** [comment]
So I'm getting this error with a fresh install running node v8.12.0 on a raspberry pi 3b+

Could still paste in my google key and have not had any functional problems - just thought you'd like to know it's still throwing this error.

The error origin is in google-assistant and according to @endoplasmic was resolved in [7f56fbc](https://github.com/endoplasmic/google-assistant/commit/7f56fbc6bc6ccd7e906c963e47fa763a7c8fbd42)

Fix has been available since google-assistant 0.5.1

**Comment by readeral** [comment]
Also not that 'opn' is now 'open' so the dependency needs updating in google-assistant

**Comment by greghesp** [comment]
Yes upgrading google-assistant will work fine. If that lib is still using opn and opn is listed as a dependency rather than open, it shouldn't cause any issues

**Comment by endoplasmic** [comment]
I went ahead and swapped to using `open` vs. `opn` now. Things seem to work just fine :)
