### ISSUE TITLE
v2 TypeError: Cannot read property 'client_id' of undefined

### ISSUE THREAD

**Issue by jimboca** [greghesp/assistant-relay#46]
I was able to run assistant-relay once and it it startup up, opened the browser and I did the authorization, and it was working, I was able to ask it to broadcast but nothing was happening.

I realized the account I used was not the main account that my Google Home's are linked to, so I created a new secret file for that user and copied it to secrets, then assistant-relay would no longer startup .  So I deleted everything and started from scratch, but still get this error.

```
pi@rpi3-2:~/assistant-relay $ ls -l server/configurations/secrets/
total 4
-rwxr--r-- 1 pi pi 364 Aug 24 20:35 jna.json
pi@rpi3-2:~/assistant-relay $ npm run start

> assistant-relay@2.0.0 start /home/pi/assistant-relay
> node server/app.js

TypeError: Cannot read property 'client_id' of undefined
    at new Auth (/home/pi/assistant-relay/node_modules/google-assistant/components/auth.js:27:38)
    at new GoogleAssistant (/home/pi/assistant-relay/node_modules/google-assistant/index.js:21:16)
    at /home/pi/assistant-relay/server/assistant.js:33:39
    at replenish (/home/pi/assistant-relay/node_modules/async/dist/async.js:1011:17)
    at /home/pi/assistant-relay/node_modules/async/dist/async.js:1016:9
    at Object.eachOfLimit (/home/pi/assistant-relay/node_modules/async/dist/async.js:1041:24)
    at Promise (/home/pi/assistant-relay/server/assistant.js:30:13)
    at new Promise (<anonymous>)
    at setupAssistant (/home/pi/assistant-relay/server/assistant.js:28:12)
    at configureUsers.then (/home/pi/assistant-relay/server/app.js:27:10)
```

**Comment by jimboca** [comment]
I generated a new json and it's now working, thanks for this!

There is an error in your example in the readme, this doesn't work on v2, right?
```
http://<ip_address>:<port>/broadcast?command="hello world"&user="greg"&broadcast=true
```
and to run on the command line I'm using this:
```
curl -d '{"command":"It has warmed up outside, close all doors and windows", "user":"jna", "broadcast":"true"}' -H "Content-Type: application/json" -X POST http://192.168.86.79:3001/assistant
```

**Comment by greghesp** [comment]
Yes, sorry seems a copy paste issue from my old readme.  Will update
