### ISSUE TITLE
Install doesn't work anymore

### ISSUE THREAD

**Issue by DanDon** [greghesp/assistant-relay#65]
Cloning the ZIP and extracting and running npm install in the directory throws errors and therefore doesn't work when finished??

```
C:\assistant-relay-master>npm install
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\form-data-455c30f0\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\form-data-455c30f0\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\form-data-455c30f0\License'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\performance-now-e8c63d77\test\mocha.opts'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\mkdirp-bd7e0a5f\bin\cmd.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\nopt-99202d38\examples\my-program.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\performance-now-e8c63d77\test\performance-now.coffee'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\mkdirp-bd7e0a5f\bin\usage.txt'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\assistant-relay-master\node_modules\.staging\node-pre-gyp-8ace9fa0\lib\util'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\protobufjs-4aa81370\docs\fonts\OpenSans-Light-webfont.eot'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\grpc-8d4e402a\node_modules\extsprintf\.gitmodules'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\grpc-8d4e402a\node_modules\extsprintf\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\assistant-relay-master\node_modules\.staging\grpc-8d4e402a\node_modules\extsprintf\jsl.node.conf'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\assistant-relay-master\node_modules\.staging\grpc-8d4e402a\node_modules\hoek\test\modules'
npm WARN assistant-relay@2.1.1 No repository field.

npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/notmasteryet/jpgjs.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.WINDOWSDAN\AppData\Roaming\npm-cache\_logs\2018-11-12T22_55_11_817Z-debug.log
```

**Comment by DanDon** [comment]
Not to worry. Figured the problem ....

... just in case anyone else has this issue and wonders what is happening:

I had not closed the same cmd window after installing Git and setting the PATH. Once the cmd window was closed and another opened. It pulled from Git and went fine :)

**Comment by brigidino** [comment]
i really cannot install i have the same issue, noway to fix it

**Comment by wasatchwired** [comment]
I have the same issue as above. Unable to install.

**Comment by wasatchwired** [comment]
Installed Git. (Was not aware that it was needed) Rebooted. Now when I install I get the following...


C:\Users\Crypto\Desktop\assistant-relay-master>npm install

> grpc@1.8.0 install C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gypgyp ERR!  stackERR!     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
 gypconfigure error
 ERR! gypstack      at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
ERR!gyp  stackERR! Error: Can't find Python executable "python", you can set the PYTHON env variable.
 gypstack      at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
ERR!gyp  stackERR!     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
 gypstack      at FSReqWrap.oncomplete (fs.js:154:21)
ERR! gypstack      at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
ERR!gyp  SystemERR! Windows_NT 10.0.17134
 stackgyp     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
 gypERR!  ERR!command  "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Crypto\\Desktop\\assistant-relay-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Crypto\\Desktop\\assistant-relay-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
stackgyp     at FSReqWrap.oncomplete (fs.js:154:21)
 ERR! cwd C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Crypto\\Desktop\\assistant-relay-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Crypto\\Desktop\\assistant-relay-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
gyp ERR! cwd C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Crypto\\Desktop\\assistant-relay-master\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Crypto\Desktop\assistant-relay-master\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Crypto\AppData\Roaming\npm-cache\_logs\2018-11-24T23_47_39_804Z-debug.log

**Comment by gizmoburdine** [comment]
I am having the exact same issue as wasatchwired any thoughts?

**Comment by wasatchwired** [comment]
gizmoburdine, I uninstalled node.js and reinstalled an older version. Version 8. It works.

**Comment by gizmoburdine** [comment]
wasatchwired,  Thanks for the tip... thought I would get creative and use 10 instead of 8 but that didn't work either.  Version 8 worked just fine though.
