### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by gadinaveh** [greghesp/assistant-relay#68]
Trying to follow the instruction, have working node on my laptop and was able to test it with google actions. 

Downloaded the latest code and ran npm install - result below, any suggestion will be welcome.

C:\Users\gadin\Documents\code\assistant-relay-2.1.1>npm install

> grpc@1.8.0 install C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.14.2 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.14.2 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gypgyp ERR!  configure error
ERR! configure error
gyp ERR!gyp  stackERR! Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
 gypstack  Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
ERR!gyp  stackERR!   File "<string>", line 1
 stackgyp    File "<string>", line 1
ERR!gyp  stackERR!     import sys; print "%s.%s.%s" % sys.version_info[:3];
 gypstack ERR!     import sys; print "%s.%s.%s" % sys.version_info[:3];
 gypstack                                 ^
ERR!gyp  stackERR!                                ^
 gypstack  SyntaxError: invalid syntax
ERR!gyp  stackERR! SyntaxError: invalid syntax
 gypstack
ERR!gyp  ERR!stack
stackgyp     at ChildProcess.exithandler (child_process.js:294:12)
 gypERR!  ERR!stack      at ChildProcess.exithandler (child_process.js:294:12)
stackgyp      at ChildProcess.emit (events.js:182:13)
ERR!gyp  stackERR!     at ChildProcess.emit (events.js:182:13)
 gypstack      at maybeClose (internal/child_process.js:962:16)
ERR!gyp  ERR!stack      at maybeClose (internal/child_process.js:962:16)
stackgyp     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
 gypERR!  stackERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
 gypSystem  Windows_NT 10.0.18298
ERR! gypSystem  Windows_NT 10.0.18298
ERR!gyp  command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\gadin\\Documents\\code\\assistant-relay-2.1.1\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\gadin\\Documents\\code\\assistant-relay-2.1.1\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
ERR!gyp command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\gadin\\Documents\\code\\assistant-relay-2.1.1\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\gadin\\Documents\\code\\assistant-relay-2.1.1\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
 ERR!gyp cwd C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc
gyp  ERR!ERR!  cwdnode -v C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc
 v10.14.2
gypgyp  ERR!ERR!  node-gyp -vnode -v v3.8.0
 v10.14.2
gypgyp  ERR!ERR!  not oknode-gyp -v
 v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.18298
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gadin\\Documents\\code\\assistant-relay-2.1.1\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc
node-pre-gyp ERR! node -v v10.14.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\gadin\Documents\code\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
npm WARN assistant-relay@2.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gadin\AppData\Roaming\npm-cache\_logs\2018-12-17T00_45_12_134Z-debug.log

**Comment by Myztillx** [comment]
What version of nodejs are you running? You can find this by typing: node -v in cmd (as shown below).
![image](https://user-images.githubusercontent.com/33730898/50063774-da80f380-017b-11e9-831e-aa35614ba8a9.png)
I had issues today when I first tried to install and found that version 8.X works.

**Comment by gadinaveh** [comment]
I tried with both 8.12 and 10.14.2 - same results.

**Comment by augusto-us** [comment]
Having a similar issue:

 grpc@1.8.0 install C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR!gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\augusto\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\augusto\\Desktop\\assistant-relay-2.1.1\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\augusto\\Desktop\\assistant-relay-2.1.1\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
gyp ERR! cwd C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
 configure error
gyp ERR! stack Error: Command failed: C:\Users\augusto\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\augusto\\Desktop\\assistant-relay-2.1.1\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\augusto\Desktop\assistant-relay-2.1.1\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
gyp[            ......] - install: info lifecycle grpc@1.8.0~install: Failed to npm WARN assistant-relay@2.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\augusto\AppData\Roaming\npm-cache\_logs\2018-12-30T00_29_50_767Z-debug.log

C:\Users\augusto\Desktop\assistant-relay-2.1.1>node -v
v10.15.0

**Comment by inguy24** [comment]
What kind of security issues are we facing by using an older version of node.js, instead what appears to be two major releases later?

**Comment by ryancasler** [comment]
Unless you port forward port 3000 on your router to your windows 10 machine....none.  And I don't see why you would do that.

**Comment by vschi** [comment]
I had a similar issue. 
I just searched on drive C:\ for "grpc_node.node" and found it in a wrong folder. 

Taking it from there and placing it in the following folder solved this problem. 
... .\assistant-relay-master\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\
