### ISSUE TITLE
Strange JSON Error

### ISSUE THREAD

**Issue by aaroneden** [greghesp/assistant-relay#70]
I have AssistantRelay successfully running on my Synology Diskstation DS1517 NAS in a docker image.

When I execute the following command (taken directly from Greg's example page) from the bash shell of the image:
`curl -v -d '{"command":"hello world", "user”:”aaron”, "broadcast":"true"}' -H "Content-Type: application/json" -X POST http://aaroneden.com:5050/assistant`

I get the following error:
`  SyntaxError: Unexpected token b in JSON at position 43<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/assistant-relay/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /assistant-relay/node_modules/body-parser/lib/read.js:121:1
8<br> &nbsp; &nbsp;at invokeCallback (/assistant-relay/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/assistant-relay/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/assistant-relay/node_modules/raw-body/index.js:273:7)<br> &nbsp; 
&nbsp;at emitNone (events.js:106:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:208:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1064:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:139:11)`

Any suggestions for how I might resolve this issue?

**Comment by aaroneden** [comment]
Okay, I figured this out.  It turns out Assistant-Relay only works with Node 8.  If you're using a different version you'll need to use NVM to do the installation and execution of Assistant-Relay with Node 8.
