### ISSUE TITLE
Problem getting module google-assistant

### ISSUE THREAD

**Issue by peterd99** [greghesp/assistant-relay#88]
I am sure user error here but have trying multiple times doing npm install over.  Downloading the files and starting again.  I keep getting stuck with error below when trying to do npm run start .  Also just looking at the configBuilder.js I only see an option for changing the port.  Following the video here for instructions it is also asking for a user name file [https://www.youtube.com/watch?v=yYVUs_mKVrM&feature=youtu.be](url)

Thank you

> assistant-relay@2.1.1 start /home/pi/assistant/assistant-relay-master
> node server/app.js

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'google-assistant'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/pi/assistant/assistant-relay-master/server/app.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assistant-relay@2.1.1 start: `node server/app.js`
npm ERR! Exit status 1

**Comment by rdgerken** [comment]
I am experiencing the same problem!  Again, could be user error... I don't really know what I'm doing, but I've tried a few different things - and getting the same result.

**Comment by greghesp** [comment]
Try entering `npm i --save google-assistant`
